version: '3.7'

services:

  deploy:
    container_name: portfolio
    image: ${DOCKER_IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
